x-service-templates:
  rinha-backend: &rinha-backend
    image: samsam1997/rinha-backend-2025:4.0
    environment:
      - REDIS_ADDR=redis:6379
      - PAYMENT_HOST_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_HOST_FALLBACK=http://payment-processor-fallback:8080
      - PAYMENT_WORKERS=200
      - PAYMENT_CHANNEL_SIZE=1000
      - DEBUG=false
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor

services:
  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000 
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "200MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend1:
    <<: *rinha-backend
    container_name: rinha-backend-1
    hostname: rinha-backend-1
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"

  backend2:
    <<: *rinha-backend
    container_name: rinha-backend-2
    hostname: rinha-backend-2
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"

  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend1:
        condition: service_started
      backend2:
        condition: service_started
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"
networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true